import operator
from typing import Annotated, Any, Dict, List, Optional
from pydantic import BaseModel, Field

class PortfolioHealth(BaseModel):
    """Analysis of the overall portfolio risk and liquidity."""
    cash_ratio_pct: float
    cash_status: str = Field(description="LOW_CASH|NORMAL|UNDER_DEPLOYED")
    overconcentrated_positions: List[str]
    overweight_sectors: List[str]
    cut_loss_candidates: List[str]
    unanalyzed_losers: List[str]

class DefensiveTrigger(BaseModel):
    """Specific defensive action triggered during portfolio health check."""
    trigger_type: str = Field(description="PROFIT_LOCK|PROFIT_LOCK_STRONG|CONCENTRATION_TRIM|SECTOR_REBALANCE|STOP_LOSS_HIT|CASH_EMERGENCY|DEAD_WEIGHT|VERDICT_DOWNGRADE")
    ticker: str
    condition_met: str
    suggested_action: str
    urgency: str = Field(description="CAO|TRUNG_BÌNH|THẤP")

class VerdictUsed(BaseModel):
    """Snippet of the analyst verdict that influenced this suggestion."""
    decision: str
    confidence_score: int
    key_bull_point: str
    key_bear_point: str

class CurrentHolding(BaseModel):
    """Current stats for the ticker being analyzed."""
    held: bool
    quantity: int
    avg_cost: float
    current_price: float
    unrealized_pnl_pct: float
    position_weight_pct: float
    days_held: int

class PriceRange(BaseModel):
    """Target entry price range."""
    low: float
    high: float

class TradeSuggestion(BaseModel):
    """Specific executable suggestion for the ticker."""
    action_rationale: str
    entry_price_range: PriceRange
    suggested_lots: int
    suggested_shares: int
    estimated_cost_vnd: float
    target_price: float
    stop_loss_price: float
    risk_reward_ratio: float
    new_avg_cost_if_add: float
    settlement_note: str
    opportunity_cost_note: str

class PortfolioImpact(BaseModel):
    """Simulated impact on the portfolio if the suggestion is followed."""
    cash_before_vnd: float
    cash_after_vnd: float
    cash_ratio_after_pct: float
    position_weight_after_pct: float
    sector_weight_after_pct: float
    concentration_warning: bool
    concentration_note: str

class WatchConditions(BaseModel):
    """Conditions for future monitoring."""
    buy_trigger: str
    sell_trigger: str

class TradeAction(BaseModel):
    """A comprehensive advisory summary generated by the Portfolio Manager."""
    ticker: str
    action: str = Field(description="MUA_MỚI|MUA_THÊM|GIỮ|CHỐT_LỜI_MỘT_PHẦN|GIẢM_TỶ_TRỌNG|CẮT_LỖ|BÁN_TOÀN_BỘ|THEO_DÕI|TĂNG_TIỀN_MẶT")
    confidence_gate_passed: bool
    
    portfolio_health: PortfolioHealth
    defensive_triggers: List[DefensiveTrigger]
    verdict_used: VerdictUsed
    current_holding: CurrentHolding
    suggestion: TradeSuggestion
    portfolio_impact: PortfolioImpact
    
    macro_alignment: str = Field(description="Hỗ trợ|Mâu thuẫn|Trung tính")
    macro_note: str
    key_risk: str
    watch_conditions: WatchConditions
    
    notes: str = Field(description="3-4 sentences in plain Vietnamese summarizing everything.")

    # Internal metadata fields (not generated by LLM but needed for system flow)
    symbol: str = ""
    status: str = "PROPOSED"
    reason: str = ""

from src.agents.analyst.state import ContextLayerAssessment

class AnalystSignal(BaseModel):
    """A structured signal received from the Analyst Graph."""
    symbol: str
    decision: str = Field(description="The final verdict decision: 'Tiềm năng', 'Khả quan', 'Trung lập', 'Rủi ro', 'An toàn'")
    confidence_score: int
    short_term_action: str
    short_term_target: float
    short_term_confidence: int
    context_layer_assessment: Optional[ContextLayerAssessment] = None
    current_price: float = Field(default=0.0, description="The latest market price used to calculate trade volumes.")

class PortfolioState(BaseModel):
    """
    The LangGraph State object holding the entire context for the Portfolio Agent.
    """
    ticker: str
    signal: AnalystSignal
    global_news: str = ""
    
    # Portfolio Context (fetched at the start of the graph)
    current_cash: float = 0.0
    current_positions: Dict[str, Any] = Field(default_factory=dict)
    total_nav: float = 0.0
    
    # Appended lists across nodes
    proposed_trades: Annotated[List[TradeAction], operator.add] = Field(default_factory=list)
    approved_trades: Annotated[List[TradeAction], operator.add] = Field(default_factory=list)
    executed_trades: Annotated[List[TradeAction], operator.add] = Field(default_factory=list)
    
    # Final status flags
    execution_status: str = Field(default="")
    errors: Annotated[List[str], operator.add] = Field(default_factory=list)
