"""Add referee fields to debate_verdicts

Revision ID: 207a55370e74
Revises: 66a8b97283a5
Create Date: 2026-03-10 18:12:35.366309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '207a55370e74'
down_revision: Union[str, Sequence[str], None] = '66a8b97283a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debate_verdicts', sa.Column('referee_action', sa.String(length=20), nullable=True))
    op.add_column('debate_verdicts', sa.Column('is_referee_valid', sa.Boolean(), nullable=True))
    op.add_column('debate_verdicts', sa.Column('referee_synthesis', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('debate_verdicts', 'referee_synthesis')
    op.drop_column('debate_verdicts', 'is_referee_valid')
    op.drop_column('debate_verdicts', 'referee_action')
    # ### end Alembic commands ###
