"""add report_path to portfolio_suggestion

Revision ID: 26f1538aef34
Revises: 96dbb200e312
Create Date: 2026-03-11 12:25:06.988088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26f1538aef34'
down_revision: Union[str, Sequence[str], None] = '96dbb200e312'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_suggestions', sa.Column('report_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio_suggestions', 'report_path')
    # ### end Alembic commands ###
