"""Add ai_summary and reporting flags

Revision ID: 2bd150843db5
Revises: 49321be884c7
Create Date: 2026-03-01 16:00:40.084974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bd150843db5'
down_revision: Union[str, Sequence[str], None] = '49321be884c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_articles', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.add_column('news_articles', sa.Column('is_summarized', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('news_articles', sa.Column('is_reported', sa.Boolean(), server_default='false', nullable=False))
    op.create_index('idx_news_unreported', 'news_articles', ['is_reported', sa.literal_column('published_at DESC')], unique=False)
    op.create_index(op.f('ix_news_articles_is_reported'), 'news_articles', ['is_reported'], unique=False)
    op.create_index(op.f('ix_news_articles_is_summarized'), 'news_articles', ['is_summarized'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_articles_is_summarized'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_is_reported'), table_name='news_articles')
    op.drop_index('idx_news_unreported', table_name='news_articles')
    op.drop_column('news_articles', 'is_reported')
    op.drop_column('news_articles', 'is_summarized')
    op.drop_column('news_articles', 'ai_summary')
    # ### end Alembic commands ###
