"""add_referee_history_to_debateverdict

Revision ID: 3772edb1c125
Revises: f6518c075894
Create Date: 2026-03-13 03:08:51.755600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3772edb1c125'
down_revision: Union[str, Sequence[str], None] = 'f6518c075894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debate_verdicts', sa.Column('referee_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('debate_verdicts', 'referee_history')
    # ### end Alembic commands ###
