"""Add financial models

Revision ID: 3ee27998c677
Revises: 2bd150843db5
Create Date: 2026-03-03 19:06:07.147075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ee27998c677'
down_revision: Union[str, Sequence[str], None] = '2bd150843db5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('short_name', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.String(length=255), nullable=True),
    sa.Column('market_cap', sa.BigInteger(), nullable=True),
    sa.Column('pe_ratio', sa.Float(), nullable=True),
    sa.Column('pb_ratio', sa.Float(), nullable=True),
    sa.Column('roe', sa.Float(), nullable=True),
    sa.Column('roa', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_profiles_industry'), 'company_profiles', ['industry'], unique=False)
    op.create_index(op.f('ix_company_profiles_last_updated'), 'company_profiles', ['last_updated'], unique=False)
    op.create_index(op.f('ix_company_profiles_sector'), 'company_profiles', ['sector'], unique=False)
    op.create_index(op.f('ix_company_profiles_ticker'), 'company_profiles', ['ticker'], unique=True)
    op.create_table('financial_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'report_type', 'period', 'year', 'quarter', name='uix_ticker_period_year_type')
    )
    op.create_index(op.f('ix_financial_reports_ingested_at'), 'financial_reports', ['ingested_at'], unique=False)
    op.create_index(op.f('ix_financial_reports_report_type'), 'financial_reports', ['report_type'], unique=False)
    op.create_index(op.f('ix_financial_reports_ticker'), 'financial_reports', ['ticker'], unique=False)
    op.create_index('idx_news_published_domain', 'news_articles', [sa.literal_column('published_at DESC'), 'domain'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_news_published_domain', table_name='news_articles')
    op.drop_index(op.f('ix_financial_reports_ticker'), table_name='financial_reports')
    op.drop_index(op.f('ix_financial_reports_report_type'), table_name='financial_reports')
    op.drop_index(op.f('ix_financial_reports_ingested_at'), table_name='financial_reports')
    op.drop_table('financial_reports')
    op.drop_index(op.f('ix_company_profiles_ticker'), table_name='company_profiles')
    op.drop_index(op.f('ix_company_profiles_sector'), table_name='company_profiles')
    op.drop_index(op.f('ix_company_profiles_last_updated'), table_name='company_profiles')
    op.drop_index(op.f('ix_company_profiles_industry'), table_name='company_profiles')
    op.drop_table('company_profiles')
    # ### end Alembic commands ###
