"""Add stock trading stats model

Revision ID: 45fb78dee135
Revises: cd39acf69fa7
Create Date: 2026-03-03 22:27:47.336547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45fb78dee135'
down_revision: Union[str, Sequence[str], None] = 'cd39acf69fa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_trading_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('trade_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_buy_vol', sa.BigInteger(), nullable=True),
    sa.Column('total_sell_vol', sa.BigInteger(), nullable=True),
    sa.Column('buy_count', sa.BigInteger(), nullable=True),
    sa.Column('sell_count', sa.BigInteger(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'trade_date', name='uix_ticker_trading_stats_date')
    )
    op.create_index(op.f('ix_stock_trading_stats_ticker'), 'stock_trading_stats', ['ticker'], unique=False)
    op.create_index(op.f('ix_stock_trading_stats_trade_date'), 'stock_trading_stats', ['trade_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_trading_stats_trade_date'), table_name='stock_trading_stats')
    op.drop_index(op.f('ix_stock_trading_stats_ticker'), table_name='stock_trading_stats')
    op.drop_table('stock_trading_stats')
    # ### end Alembic commands ###
