"""Add context_layer_assessment to debate_verdicts

Revision ID: 54e1d9f1097d
Revises: 26f1538aef34
Create Date: 2026-03-11 14:27:00.181194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54e1d9f1097d'
down_revision: Union[str, Sequence[str], None] = '26f1538aef34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debate_verdicts', sa.Column('context_layer_assessment', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('debate_verdicts', 'context_layer_assessment')
    # ### end Alembic commands ###
