"""Add technicals and valuations

Revision ID: 66a8b97283a5
Revises: b6b0a481fcd7
Create Date: 2026-03-09 21:11:29.490591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66a8b97283a5'
down_revision: Union[str, Sequence[str], None] = 'b6b0a481fcd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_profiles', sa.Column('eps', sa.Float(), nullable=True))
    op.add_column('company_profiles', sa.Column('ev_ebitda', sa.Float(), nullable=True))
    op.add_column('stock_eod', sa.Column('rsi', sa.Float(), nullable=True))
    op.add_column('stock_eod', sa.Column('macd', sa.Float(), nullable=True))
    op.add_column('stock_eod', sa.Column('macd_signal', sa.Float(), nullable=True))
    op.add_column('stock_eod', sa.Column('macd_hist', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_eod', 'macd_hist')
    op.drop_column('stock_eod', 'macd_signal')
    op.drop_column('stock_eod', 'macd')
    op.drop_column('stock_eod', 'rsi')
    op.drop_column('company_profiles', 'ev_ebitda')
    op.drop_column('company_profiles', 'eps')
    # ### end Alembic commands ###
