"""Add shareholders and officers to Company

Revision ID: 835871710581
Revises: c7a6e1f16bee
Create Date: 2026-03-03 19:50:49.529629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '835871710581'
down_revision: Union[str, Sequence[str], None] = 'c7a6e1f16bee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_profiles', sa.Column('shareholders', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('company_profiles', sa.Column('officers', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_profiles', 'officers')
    op.drop_column('company_profiles', 'shareholders')
    # ### end Alembic commands ###
