"""Add debate_rounds to DebateVerdict

Revision ID: 8917dba1a98c
Revises: 54e1d9f1097d
Create Date: 2026-03-13 02:33:36.811710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8917dba1a98c'
down_revision: Union[str, Sequence[str], None] = '54e1d9f1097d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debate_verdicts', sa.Column('debate_rounds', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('debate_verdicts', 'debate_rounds')
    # ### end Alembic commands ###
