"""Add PortfolioSuggestion table

Revision ID: 96dbb200e312
Revises: 52ab0ad1aeb0
Create Date: 2026-03-11 11:26:29.432050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96dbb200e312'
down_revision: Union[str, Sequence[str], None] = '52ab0ad1aeb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_suggestions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('analyst_decision', sa.String(length=255), nullable=False),
    sa.Column('analyst_confidence', sa.Integer(), nullable=False),
    sa.Column('suggested_action', sa.String(length=20), nullable=False),
    sa.Column('suggested_shares', sa.Integer(), nullable=False),
    sa.Column('suggested_price', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_suggestions_symbol'), 'portfolio_suggestions', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_suggestions_symbol'), table_name='portfolio_suggestions')
    op.drop_table('portfolio_suggestions')
    # ### end Alembic commands ###
