"""Add StockEOD table

Revision ID: a53287f1b29d
Revises: e5b9f1f1b98a
Create Date: 2026-03-03 19:30:45.506355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a53287f1b29d'
down_revision: Union[str, Sequence[str], None] = 'e5b9f1f1b98a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_eod',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('trade_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'trade_date', name='uix_ticker_trade_date')
    )
    op.create_index(op.f('ix_stock_eod_ticker'), 'stock_eod', ['ticker'], unique=False)
    op.create_index(op.f('ix_stock_eod_trade_date'), 'stock_eod', ['trade_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_eod_trade_date'), table_name='stock_eod')
    op.drop_index(op.f('ix_stock_eod_ticker'), table_name='stock_eod')
    op.drop_table('stock_eod')
    # ### end Alembic commands ###
