"""Add DebateVerdict

Revision ID: b6b0a481fcd7
Revises: 45fb78dee135
Create Date: 2026-03-09 19:19:45.822118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6b0a481fcd7'
down_revision: Union[str, Sequence[str], None] = '45fb78dee135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debate_verdicts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('bull_score', sa.Integer(), nullable=False),
    sa.Column('bear_score', sa.Integer(), nullable=False),
    sa.Column('short_term', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('medium_term', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('long_term', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('judge_synthesis', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debate_verdicts_created_at'), 'debate_verdicts', ['created_at'], unique=False)
    op.create_index(op.f('ix_debate_verdicts_is_active'), 'debate_verdicts', ['is_active'], unique=False)
    op.create_index(op.f('ix_debate_verdicts_ticker'), 'debate_verdicts', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_debate_verdicts_ticker'), table_name='debate_verdicts')
    op.drop_index(op.f('ix_debate_verdicts_is_active'), table_name='debate_verdicts')
    op.drop_index(op.f('ix_debate_verdicts_created_at'), table_name='debate_verdicts')
    op.drop_table('debate_verdicts')
    # ### end Alembic commands ###
