"""Add phase 4 market intelligence models

Revision ID: cd39acf69fa7
Revises: 835871710581
Create Date: 2026-03-03 20:33:49.520276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd39acf69fa7'
down_revision: Union[str, Sequence[str], None] = '835871710581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commodity_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('price_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'price_date', name='uix_commodity_price_date')
    )
    op.create_index(op.f('ix_commodity_prices_price_date'), 'commodity_prices', ['price_date'], unique=False)
    op.create_index(op.f('ix_commodity_prices_symbol'), 'commodity_prices', ['symbol'], unique=False)
    op.create_table('macro_indicators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('report_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'report_date', name='uix_macro_indicator_date')
    )
    op.create_index(op.f('ix_macro_indicators_name'), 'macro_indicators', ['name'], unique=False)
    op.create_index(op.f('ix_macro_indicators_report_date'), 'macro_indicators', ['report_date'], unique=False)
    op.create_table('market_index_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('index_code', sa.String(length=20), nullable=False),
    sa.Column('trade_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pe', sa.Float(), nullable=True),
    sa.Column('pb', sa.Float(), nullable=True),
    sa.Column('dividend_yield', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index_code', 'trade_date', name='uix_index_trade_date')
    )
    op.create_index(op.f('ix_market_index_stats_index_code'), 'market_index_stats', ['index_code'], unique=False)
    op.create_index(op.f('ix_market_index_stats_trade_date'), 'market_index_stats', ['trade_date'], unique=False)
    op.create_table('mutual_fund_nav',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fund_code', sa.String(length=50), nullable=False),
    sa.Column('nav_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('nav', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fund_code', 'nav_date', name='uix_fund_nav_date')
    )
    op.create_index(op.f('ix_mutual_fund_nav_fund_code'), 'mutual_fund_nav', ['fund_code'], unique=False)
    op.create_index(op.f('ix_mutual_fund_nav_nav_date'), 'mutual_fund_nav', ['nav_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mutual_fund_nav_nav_date'), table_name='mutual_fund_nav')
    op.drop_index(op.f('ix_mutual_fund_nav_fund_code'), table_name='mutual_fund_nav')
    op.drop_table('mutual_fund_nav')
    op.drop_index(op.f('ix_market_index_stats_trade_date'), table_name='market_index_stats')
    op.drop_index(op.f('ix_market_index_stats_index_code'), table_name='market_index_stats')
    op.drop_table('market_index_stats')
    op.drop_index(op.f('ix_macro_indicators_report_date'), table_name='macro_indicators')
    op.drop_index(op.f('ix_macro_indicators_name'), table_name='macro_indicators')
    op.drop_table('macro_indicators')
    op.drop_index(op.f('ix_commodity_prices_symbol'), table_name='commodity_prices')
    op.drop_index(op.f('ix_commodity_prices_price_date'), table_name='commodity_prices')
    op.drop_table('commodity_prices')
    # ### end Alembic commands ###
