"""Change quarter to non-nullable with default 0

Revision ID: e5b9f1f1b98a
Revises: 28bea80b9599
Create Date: 2026-03-03 19:18:25.725249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5b9f1f1b98a'
down_revision: Union[str, Sequence[str], None] = '28bea80b9599'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('financial_reports', 'quarter',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('financial_reports', 'quarter',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
