"""add_verdict_id_to_portfoliosuggestion

Revision ID: f6518c075894
Revises: 8917dba1a98c
Create Date: 2026-03-13 02:49:01.326356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6518c075894'
down_revision: Union[str, Sequence[str], None] = '8917dba1a98c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_suggestions', sa.Column('verdict_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_portfolio_suggestions_verdict_id'), 'portfolio_suggestions', ['verdict_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_suggestions_verdict_id'), table_name='portfolio_suggestions')
    op.drop_column('portfolio_suggestions', 'verdict_id')
    # ### end Alembic commands ###
