import asyncio
import sys
import warnings

# Suppress Pandas FutureWarnings/DeprecationWarnings generated by 3rd-party libs (like vnstock)
warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore", category=DeprecationWarning)

import structlog
from src.config.settings import settings

from src.agents.financial.worker import FinancialWorker
from src.agents.news.scheduler import NewsScheduler

logger = structlog.get_logger(__name__)

async def main():
    logger.info("xalpha_researcher_starting", version="0.1.2")
    
    # Initialize workers
    financial_worker = FinancialWorker()
    news_scheduler = NewsScheduler()

    logger.info("starting_system_services")
    
    # 1. Start Schedulers (Non-blocking)
    financial_worker.start() # Adds jobs and starts APScheduler
    news_scheduler.start()   # Adds jobs and starts APScheduler
    
    # 2. Trigger immediate financial sync check
    # This is what handles the AUTOMATIC BOOTSTRAP if the DB is empty.
    asyncio.create_task(financial_worker.run_daily_sync())
    
    logger.info("system_services_running", 
                note="Financial bootstrap will trigger automatically if DB is empty.")
    
    try:
        # Keep the main process alive
        while True:
            await asyncio.sleep(3600)
    except (KeyboardInterrupt, SystemExit):
        logger.info("system_shutdown")
        financial_worker.scheduler.shutdown()
        news_scheduler.scheduler.shutdown()

if __name__ == "__main__":
    asyncio.run(main())
